### ISSUE TITLE
About the Dataset

### ISSUE THREAD

**Issue by ShaneSpace** [mohamedr002/CCDG#1]
Hi, thank you very much for your sharing.
I found that the following link is not accessible
"1- Download datasets from the following link: https://drive.google.com/file/d/1-QdDtOqU9eV5liMmYno5LsZpdx3vuRHT/view?usp=sharing"

Could you please update the latest link of the dataset preprocessing?

**Comment by mohamedr002** [comment]
Hi, thanks for using our work, 

Yes, sure here are the data files

https://researchdata.ntu.edu.sg/dataverse/ccdg
